name=RVLESP32WiFi
version=1.0.0
author=Bryan Hughes <bryan@nebri.us>
maintainer=Bryan Hughes <bryan@nebri.us>
sentence=An implementation of RVL based on the Arduino framework for the ESP32 using async UDP
paragraph=For more information, visit https://github.com/rvl-system/rvl-esp32-wifi
category=Communication
url=https://github.com/rvl-system/rvl-esp32-wifi
architectures=esp32
